version: '2'
services:
  spiderenv:
    build:
      context: ./
      dockerfile: docker/Dockerfile-python
    command: ./run_spider.sh
    volumes:
      - .:/src/app
    ports:
      - "8801:8801"
    links:
      - datamining
      - redis
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  datamining:
    image: spiderenv
    command: ./run_dataMining.sh
    volumes:
      - .:/src/app
    ports:
      - "8802:8802"
    links:
      - spiderenv
      - redis
    depends_on:
      - redis